### ISSUE TITLE
forever stop <pid> stops ALL processes (behaves like stopall)

### ISSUE THREAD

**Issue by eric-tucker** [foreverjs/forever#659]
Easy to reproduce.  Start two node services using forever.  Try to stop one using the process ID.  Forever stops ALL processes:

````
[root@ip-10-200-81-145 builds]# FOREVER_ROOT=/var/run/forever forever list
info:    Forever processes running
data:        uid  command script      forever pid   id logfile                               uptime      
data:    [0] Oquh node    app.js 3200 17625   17646    /var/log/forever/3200.log    0:0:0:34.622
data:    [1] hWkI node    app.js 3000 18068   18070    /var/log/forever/3000.log    0:0:0:18.858
data:    [2] mv1U node    app.js 3151 18482   18520    /var/log/forever/3151.log    0:0:0:6.273 
[root@ip-10-200-81-145 builds]# FOREVER_ROOT=/var/run/forever forever stop 18520
info:    Forever stopped process:
    uid  command script      forever pid   id logfile                               uptime
[0] Oquh node    app.js 3200 17625   17646    /var/log/forever/3200.log    0:0:1:50.470
[1] hWkI node    app.js 3000 18068   18070    /var/log/forever/3000.log    0:0:1:34.707
[2] mv1U node    app.js 3151 18482   18520    /var/log/forever/3151.log    0:0:1:22.122
[root@ip-10-200-81-145 builds]# FOREVER_ROOT=/var/run/forever forever list
info:    No forever processes running
[root@ip-10-200-81-145 builds]#
````

**Comment by derEremit** [comment]
Just updated and killed a bunch of live processes
Seriously critical issue!!!!!
forever v 14.0

**Comment by eric-tucker** [comment]
How could this be missed?  Do you not have regression tests?  This is a critical bug.

**Comment by jcrugzz** [comment]
Very odd indeed, this should not have gotten past tests. @Tjatse this seems to be related to your work around stop, could you look into this?

**Comment by Tjatse** [comment]
Sorry about the confusions, the test suit does not coverage this, try to manually update your local codes like below:
[https://github.com/foreverjs/forever/blob/master/lib/forever.js#L232-L236](https://github.com/foreverjs/forever/blob/master/lib/forever.js#L232-L236)
```javascript
      procs = forever.findById(target, processes)
        || forever.findByIndex(target, processes)
        || forever.findByUid(target, processes)
        || forever.findByPid(target, processes);
```

Actually, this is an unfinished work, there still have too much PRs from my repository, but have no time to wait for approving.

Any way, glad to help solve this, and again, sorry for the bug, guys!
My forked repository has been deleted, so, anyone could help to send a PR will be appreciated.

**Comment by indexzero** [comment]
Hah. Sorry you're not sorry? We'll figure it out. So we should expect more bugs from your other PR?

**Comment by Tjatse** [comment]
Weird tone :( 
This is totally unexpected, I just wanna to help to make this tool better, if you think I am doing a wrong thing, and curse me for that, I think I deserved.

I've figure it out, and always glad to do that. I still do the jobs but not only say **Sorry**, right?

**Comment by derEremit** [comment]
No matter what happens with this issue, but someone should immediately pull the release 0.14 from npm (if that's possible) before more people upgrade and kill all their running processes!!!!

**Comment by jcrugzz** [comment]
@Tjatse I don't believe @indexzero understands your tone here either. It seems you submitted unfinished work that was finished in a later pull-request. This creates mismatched expectations of what a patch consists of if it was expected to be unfinished. What he is trying to build here is trust. He likes that you are enthusiastic about helping but patience and attention to detail are crucial in a project that has many people who depend on it. A thorough review process is required and when there is not time for that, pull-requests can sit for a while. I understand this is difficult as the contributor as you want to help and see your patches land, but trust needs to be built in the beginning. Things do not always operate at a rapid pace, and that can be for good reason. If trust can be earned through the learning process that happens through open source contribution, things can move faster, but its obviously not at that point yet.

@derEremit It has been unpublished

**Comment by gregoryb** [comment]
Any news about the release ?

**Comment by nameanyone** [comment]
Somehow this re-surfaced, this time only when <pid> is zero.

**Comment by sharjeel-ahmed** [comment]
When pid is zero it terminates all processes, a serious bug, i ended up terminating all processes.

**Comment by softius** [comment]
It appears that the commands `stop 0` and `restart 0` function exactly like `stopall` and `restartall`. This is very critical.

**Comment by sharjeel-ahmed** [comment]
The problem has not gone away yet.

**Comment by bdmayes** [comment]
I can confirm that I am seeing the same behavior. Executing ```forever stop 0``` results in all running processes being terminated.

**Comment by rodikh** [comment]
+1
Here too, when running `forever stop 0` all processes stop.

**Comment by JamieMcNaught** [comment]
This has been fixed in the main codebase (see pull request https://github.com/foreverjs/forever/pull/756) but there hasn't been a release since then. My companies current deployment system is using a custom build including this fix which we deploy via:

```
npm install -g git://github.com/JamieMcNaught/forever.git
```

You can do similar with the current dev branch of forever using something like:

```
npm install -g git://github.com/foreverjs/forever.git
```

However with both solutions, bear in mind that either of these branches could be horribly broken when compared to a proper release (albeit my branch has been used in production for a while now and I don't intend to make any changes to it).

**Comment by stevenmyhre** [comment]
+1 Still seeing this, 

`forever stop 0` is stopping all processes

any updates?

**Comment by JamieMcNaught** [comment]
@stevenmyhre  - have you tried with of the git repo's mentioned in my previous comment (Dec 02 2015)? I've been using this successfully for a number of projects.

**Comment by stevenmyhre** [comment]
No, I'll wait for the official release

**Comment by indexzero** [comment]
This was fixed in `0.15.2`
