### ISSUE TITLE
Forever erroneously pops up console window when executing child process calls

### ISSUE THREAD

**Issue by jonrhall** [foreverjs/forever#767]
Working with Forever, trying to stand up a fairly simple node server which makes remote calls to a C# client. If you run the script/server directly, no popup console windows will appear, but when run with forever, every time the server wants to execute a remote command, a console window appears and then disappears after the remote command is finished.

Reproducible on:
-Windows 7 Ultimate
-Node v0.12+ or v4.0+
-npm v3
-Forever 0.15.1

Trivial code example that replicates the error:

	var http = require('http'),
	    exec = require('child_process').exec,
	    server;
		
	server = http.createServer(function (request, response) {
		var child;
		
		if (request.url != '/') {
			response.writeHead(404);
			return response.end();
		}

		response.writeHead(200, {"Content-Type": "text/plain"});
		
		child = exec('ping localhost -n 2', {}, function(error, stdout, stderr) {
			response.write(stdout);
		}).on('close', function(code) {
			response.end();
		});
	});

	server.listen(8000);

Is there some kind of bug with Forever itself, or is this some configuration option that I'm missing?

**Comment by niravpatel2008** [comment]
I am also facing this kind of issue.

below code works with node test.js but when i try run with forever start test.js it wont execute exec.

any alternative way?????

```
var terminal = require('child_process').spawn('bash');
terminal.stdout.on('data', function (data) {
    console.log('stdout: ' + data);
});
terminal.on('exit', function (code) {
    console.log('child process exited with code ' + code);
});
setTimeout(function() {
    console.log('Sending stdin to terminal');
    terminal.stdin.write("whomi\n");
    terminal.stdin.write("sudo ssh instance-solr-1.us-central1-b.versatile-nomad-126504 \"sudo su | . /root/file
.sh >>/dev/null 2>/dev/null\" &\n");
    console.log('Ending terminal session');
    terminal.stdin.end();
}, 1000);
```

**Comment by jpek42** [comment]
We were able to work around this by creating a separate small EXE (on Windows), which does the exec of the child program, setting the correct flags to avoid the process window. I'm not sure that the above comment is the same issue, as our child process was actually running.

**Comment by niravpatel2008** [comment]
Thanks @jpek42 , i figure out the issue actually my cmd command required terminal session for stdout. thats why its not getting executed now i have changed the way of execution of command which ignore stdout and detach child process from parent and its working fine :)


Thanks again

**Comment by r-pr** [comment]
@jonrhall: passing `{ windowsHide: true }` instead of empty options object to `exec()` should fix the problem

**Comment by marcus13345** [comment]
This may be better put into another issue, as i don't want to full necro this thread. But the issue still remains for uses cases such as have a webpack watch daemon. webpack's subprocess (as well as im sure, many other packages that utilise child process) dont implement this feature, and as a developer theres no way for me to disable it without manually changing webpack code.

This definitely edges on `wont fix` territory, as it should be up to other packages to make code that complies with the API, however, many dont, and some form of solution would be a life saver.
