### ISSUE TITLE
`forever stop 0` stops all processes

### ISSUE THREAD

**Issue by vladh** [foreverjs/forever#814]
I just took down an entire production server due to this.

Steps:
1. `forever start a`
2. `forever start b`
3. `forever stop 0`

All processes are then killed.

**Comment by egirshov** [comment]
I believe this is the same as #699 which is apparently already fixed in the master. Sad that there is not update published to npm yet

**Comment by fresheneesz** [comment]
Ugh really? Why is this still open? This is a huge freaking problem...

**Comment by ultimate-tester** [comment]
This issue should be marked as a duplicate of #699 
Unfortunately the issue still exists because the latest code is not released to npm yet.

**Comment by fresheneesz** [comment]
I recently switched to pm2 - SO much better. Screw this waiting for years for huge bugs to be fixed.

**Comment by vladh** [comment]
We also switched to pm2.

**Comment by indexzero** [comment]
This was fixed in `forever@0.15.2`
